[2025-10-02T01:05:27.911+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-02T01:05:27.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sentiment140_end2end_single.download_raw_from_s3 manual__2025-10-02T01:05:24.833723+00:00 [queued]>
[2025-10-02T01:05:27.919+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sentiment140_end2end_single.download_raw_from_s3 manual__2025-10-02T01:05:24.833723+00:00 [queued]>
[2025-10-02T01:05:27.919+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-02T01:05:27.923+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_raw_from_s3> on 2025-10-02 01:05:24.833723+00:00
[2025-10-02T01:05:27.930+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5953) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-02T01:05:27.931+0000] {standard_task_runner.py:63} INFO - Started process 5956 to run task
[2025-10-02T01:05:27.930+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sentiment140_end2end_single', 'download_raw_from_s3', 'manual__2025-10-02T01:05:24.833723+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/edaproject.py', '--cfg-path', '/tmp/tmp5pow9mjs']
[2025-10-02T01:05:27.931+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask download_raw_from_s3
[2025-10-02T01:05:27.948+0000] {task_command.py:426} INFO - Running <TaskInstance: sentiment140_end2end_single.download_raw_from_s3 manual__2025-10-02T01:05:24.833723+00:00 [running]> on host 619c97ee2164
[2025-10-02T01:05:27.977+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sentiment140_end2end_single' AIRFLOW_CTX_TASK_ID='download_raw_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T01:05:24.833723+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T01:05:24.833723+00:00'
[2025-10-02T01:05:27.978+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-02T01:05:27.983+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-02T01:05:27.983+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/edaproject.py", line 82, in _download_raw_from_s3
    assert CSV_S3_URI and CSV_S3_URI.startswith("s3://"), "Set CSV_S3_URI like s3://bucket/path/main-data.csv"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Set CSV_S3_URI like s3://bucket/path/main-data.csv
[2025-10-02T01:05:27.989+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=sentiment140_end2end_single, task_id=download_raw_from_s3, run_id=manual__2025-10-02T01:05:24.833723+00:00, execution_date=20251002T010524, start_date=20251002T010527, end_date=20251002T010527
[2025-10-02T01:05:27.994+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task download_raw_from_s3 (Set CSV_S3_URI like s3://bucket/path/main-data.csv; 5956)
[2025-10-02T01:05:28.028+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-02T01:05:28.032+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
[2025-10-02T01:05:28.037+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-02T01:05:28.037+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
