[2025-10-02T02:27:18.254+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-02T02:27:18.260+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sentiment140_end2end_single.download_raw_from_s3 manual__2025-10-02T02:27:13.521959+00:00 [queued]>
[2025-10-02T02:27:18.263+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sentiment140_end2end_single.download_raw_from_s3 manual__2025-10-02T02:27:13.521959+00:00 [queued]>
[2025-10-02T02:27:18.264+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-02T02:27:18.268+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_raw_from_s3> on 2025-10-02 02:27:13.521959+00:00
[2025-10-02T02:27:18.272+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=141) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-02T02:27:18.272+0000] {standard_task_runner.py:63} INFO - Started process 143 to run task
[2025-10-02T02:27:18.273+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sentiment140_end2end_single', 'download_raw_from_s3', 'manual__2025-10-02T02:27:13.521959+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/edaproject.py', '--cfg-path', '/tmp/tmpc26utw06']
[2025-10-02T02:27:18.274+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask download_raw_from_s3
[2025-10-02T02:27:18.297+0000] {task_command.py:426} INFO - Running <TaskInstance: sentiment140_end2end_single.download_raw_from_s3 manual__2025-10-02T02:27:13.521959+00:00 [running]> on host 7be8b7489da9
[2025-10-02T02:27:18.329+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sentiment140_end2end_single' AIRFLOW_CTX_TASK_ID='download_raw_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T02:27:13.521959+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T02:27:13.521959+00:00'
[2025-10-02T02:27:18.329+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-02T02:27:18.335+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-02T02:27:18.335+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/edaproject.py", line 88, in _download_raw_from_s3
    raise ValueError(
ValueError: CSV_S3_URI is not set or invalid. Set it as env var or Airflow Variable. Example: s3://298a1/sentiment140/***/main-data.csv
[2025-10-02T02:27:18.339+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=sentiment140_end2end_single, task_id=download_raw_from_s3, run_id=manual__2025-10-02T02:27:13.521959+00:00, execution_date=20251002T022713, start_date=20251002T022718, end_date=20251002T022718
[2025-10-02T02:27:18.344+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task download_raw_from_s3 (CSV_S3_URI is not set or invalid. Set it as env var or Airflow Variable. Example: s3://298a1/sentiment140/***/main-data.csv; 143)
[2025-10-02T02:27:18.370+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-02T02:27:18.379+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-02T02:27:18.380+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
