[2025-10-02T05:52:01.835+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-02T05:52:01.887+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sentiment140_end2end_single.download_raw_from_s3 manual__2025-10-02T05:46:55.254637+00:00 [queued]>
[2025-10-02T05:52:01.901+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sentiment140_end2end_single.download_raw_from_s3 manual__2025-10-02T05:46:55.254637+00:00 [queued]>
[2025-10-02T05:52:01.901+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-02T05:52:01.907+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_raw_from_s3> on 2025-10-02 05:46:55.254637+00:00
[2025-10-02T05:52:01.912+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=431) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-02T05:52:01.914+0000] {standard_task_runner.py:63} INFO - Started process 433 to run task
[2025-10-02T05:52:01.914+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sentiment140_end2end_single', 'download_raw_from_s3', 'manual__2025-10-02T05:46:55.254637+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/edaproject.py', '--cfg-path', '/tmp/tmpo7bvb5b1']
[2025-10-02T05:52:01.915+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask download_raw_from_s3
[2025-10-02T05:52:01.944+0000] {task_command.py:426} INFO - Running <TaskInstance: sentiment140_end2end_single.download_raw_from_s3 manual__2025-10-02T05:46:55.254637+00:00 [running]> on host 590373856cb4
[2025-10-02T05:52:01.979+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sentiment140_end2end_single' AIRFLOW_CTX_TASK_ID='download_raw_from_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T05:46:55.254637+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T05:46:55.254637+00:00'
[2025-10-02T05:52:01.980+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-02T05:52:01.987+0000] {logging_mixin.py:188} INFO - [download_raw_from_s3] Using CSV_S3_URI=s3://298a1/sentiment140/***/main-data.csv
[2025-10-02T05:52:01.992+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-10-02T05:52:01.992+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-10-02T05:52:02.746+0000] {s3.py:1387} INFO - Downloading source S3 file from Bucket 298a1 with path sentiment140/***/main-data.csv
[2025-10-02T05:52:03.272+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-02T05:52:03.273+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/edaproject.py", line 120, in _download_raw_from_s3
    hook.download_file(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1413, in download_file
    file = NamedTemporaryFile(dir=local_path, prefix="airflow_tmp_", delete=False)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/tempfile.py", line 582, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/tempfile.py", line 579, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/MAUD_train_raw.csv/airflow_tmp_19n9oe2k'
[2025-10-02T05:52:03.279+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sentiment140_end2end_single, task_id=download_raw_from_s3, run_id=manual__2025-10-02T05:46:55.254637+00:00, execution_date=20251002T054655, start_date=20251002T055201, end_date=20251002T055203
[2025-10-02T05:52:03.285+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task download_raw_from_s3 ([Errno 2] No such file or directory: '/tmp/MAUD_train_raw.csv/airflow_tmp_19n9oe2k'; 433)
[2025-10-02T05:52:03.328+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-02T05:52:03.341+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-02T05:52:03.343+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
